# Generated by Django 3.2.9 on 2022-01-14 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20220114_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='catg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='auctions.category'),
        ),
    ]
